networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
  webui:
    internal: false
  worker:
    internal: true

services:
  hasher:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    expose:
      - 8080
    healthcheck:
      interval: 10s
      retry: 3
      start_period: 30s
      test: wget -q --spyder localhost:8080
      timeout: 1s
    image: ccervigonavila/dockercoins:latest-hasher
    networks:
      - hasher
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    expose:
      - 8080
    healthcheck:
      interval: 10s
      retry: 3
      start_period: 30s
      test: redis -cli
      timeout: 1s
    image: redis:6.0.9-alpine3.12@sha256:aa31e6d2afc72d2222ed3953587197c324f615861771637a64053f9d99ba4b74
    networks:
      - redis
    volumes:
      - redis:/data
  rng:
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    expose:
      - 8080
    healthcheck:
      interval: 10s
      retry: 3
      start_period: 30s
      test: wget -q --spyder localhost:8080
      timeout: 1s
    image: ccervigonavila/dockercoins:latest-rng
    networks:
      - rng
  webui:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    expose:
      - 8080
    healthcheck:
      interval: 10s
      retry: 3
      start_period: 30s
      test: curl -f localhost:8080
      timeout: 1s
    image: ccervigonavila/dockercoins:latest-webui
    networks:
      - webui
      - redis
  worker:
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    healthcheck:
      interval: 10s
      retry: 3
      start_period: 30s
      test: netstat -nt | grep ESTABLISHED | grep -q 6379
      timeout: 1s
    image: ccervigonavila/dockercoins:latest-worker
    networks:
      - hasher
      - redis
      - rng
      - worker
